import Link from 'next/link';
import { asset } from '@/lib/assets';
import { hulioMetadata } from '@/lib/metadata';
import { Arrow, Button, Counter, Reveal, SectionLabel, TeamGrid, TeamCard, VideoBlock } from '@/components/shared';
import { KeywordTicker, MovingCTA, Testimonials } from '@/components/home-interactions';
import { ProjectGrid, BlogGrid } from '@/components/collections/grids';
import { HeroCopy } from '@/components/hero-copy';
import './home.css';
export const metadata = hulioMetadata('Creative Digital Agency', '/hulio');
const services = [['Brand Identity Design', 'We help businesses build strong visual identities that reflect their personality, values, and voice.', 'DsGFfQx6r95GsPBKTESfRV5BlzY.png'], ['Web Design & Development', 'Discover how to create powerful branding that captures your audience’s attention, builds trust.', 'ybzmcw5btszxb0VnjRgHdAaaNsw.png'], ['UI/UX Design', 'We design intuitive interfaces and seamless user experiences that enhance usability and keep your audience engaged.', 'O22zKtjSwbjcV3P39WYWpN6FkxQ.png'], ['Brand Identity Design', 'Through SEO, PPC, and content strategy, we connect your brand with the right audience and drive measurable growth.', 'MVdW2nkH9wEqMfmZt7P1K2Lew.png']];
export default function HulioHome() {
    return <>
    <section className="home-hero"><div className="hero-grid-decoration" aria-hidden="true"/><div className="container hero-content"><HeroCopy /><div className="hero-art"><img className="hero-photo" src={asset('U35vkZ36iBOOSSG0KzgO0Ajdm0.png')} alt="Creative team collaborating in the Hulio studio" width="1574" height="1860" fetchPriority="high"/><img className="hero-cutout hero-cutout-1" src="/hulio/hero-cutout-1.svg" alt=""/><img className="hero-cutout hero-cutout-2" src="/hulio/hero-cutout-2.svg" alt=""/><img className="hero-cutout hero-cutout-3" src="/hulio/hero-cutout-3.svg" alt=""/><div className="hero-seal" aria-hidden="true"><svg viewBox="0 0 120 120"><defs><path id="seal-circle" d="M60 60m-49 0a49 49 0 1 1 98 0a49 49 0 1 1-98 0"/></defs><text><textPath href="#seal-circle">ILLUSTRATIONS · WEBSITES · APPLICATIONS · MOBILE · </textPath></text></svg><img src={asset('aMPobmzwe3VrzSPg4U6YmBkc1Es.png')} width="74" height="74" alt=""/></div><span className="hero-square" aria-hidden="true"/></div></div></section>
    <KeywordTicker />
    <section className="home-features"><div className="container feature-grid">{[['Who we are & what we do', 'Discover our identity, mission, and the impactful work we do to make a difference.', 'about'], ['We’ll design your projects', 'Turning your vision into reality with expert design and precision execution.', 'project'], ['Drop us your message!', 'Your ideas, our inbox. Let’s make it happen! Share your vision & we’ll bring it to life.', 'contact']].map(([title, text, href]) => <article key={href}><h4>{title}</h4><p>{text}</p><Link href={'/hulio/' + href} className="text-link">Learn more <Arrow /></Link></article>)}</div></section>
    <section className="home-about"><div className="container about-grid"><SectionLabel>Who we are</SectionLabel><Reveal><h3>We deliver innovative ideas to help grow your startup — agency.</h3></Reveal><div className="about-orb"><img src={asset('OQy3Iv3lQ40QKCoLU4u2Bj6cysY.png')} alt="" width="210" height="214" loading="lazy"/></div><div className="about-bottom"><div><Counter value={15} suffix="M+"/><p>We’ve helped companies secure over $15M with confidence.</p></div><div><p>Today, consumers heavily rely on digital channels to research products and services. In fact, 51% of consumers thoroughly research a brand before engaging with it.</p><Button href="/hulio/about" variant="blue">Explore Us More</Button></div></div></div></section>
    <section className="container home-video"><VideoBlock /></section>
    <section className="home-clients"><div className="container"><h4>Worlds Most Popular Companies Trust Us</h4><p>Connect with us &amp; let’s build something cool together</p><div className="client-logos">{['/hulio/client-logo-0.svg', '/hulio/client-logo-1.svg', '/hulio/client-logo-2.svg', '/hulio/client-logo-3.svg', '/hulio/client-logo-4.svg', '/hulio/client-logo-5.svg'].map((src, i) => <img key={src} src={src} alt={`Client partner ${i + 1}`} width="155" height="44" loading="lazy"/>)}</div></div></section>
    <section className="home-projects"><div className="container"><SectionLabel>Who we are</SectionLabel><h2 className="section-heading">Take a look at our projects</h2><div className="home-grid-gap"><ProjectGrid limit={4} loadMore/></div></div></section>
    <section className="home-services"><div className="container"><div className="service-heading"><div><SectionLabel>Our Services</SectionLabel><h2 className="section-heading">What we offer</h2><p>With every single one of our clients we bring forth a deep passion for creative roblem solving innovations forward thinking brands boundaries</p></div><Button href="/hulio/contact" className="service-cta">Let&apos;s Talk with Us</Button></div><div className="service-list">{services.map(([title, description, image], i) => <Link className="service-row" href="/hulio/contact" key={i}><span className="service-number">0{i + 1}</span><h4>{title}</h4><p>{description}</p><img className="service-preview" src={asset(image)} alt="" width="150" height="100" loading="lazy"/><span className="service-arrow"><Arrow /></span></Link>)}</div></div></section>
    <section className="home-team"><div className="container"><SectionLabel>Our Awesome Team</SectionLabel><h2 className="section-heading">Meet the team</h2><div className="home-grid-gap"><TeamGrid limit={3}/></div><div className="team-last-row"><TeamCard index={3}/><div className="team-message" style={{ backgroundImage: `url(${asset('cD6V0pj2urFNhdfagyiTwf2Vbk.svg')})` }}><h3>Our Awesome Team</h3><p>The Neural Network experts: uniting talent for intelligent solutions</p><div><div><Counter value={250} suffix="+"/><h5>Awesome team members</h5></div><Button href="/hulio/team">Meet our team</Button></div></div></div></div></section>
    <section className="home-testimonials"><div className="container"><SectionLabel>Testimonials</SectionLabel><h2 className="section-heading">What our users<br />say about us.</h2><Testimonials /></div></section>
    <section className="home-blog"><div className="container"><div className="blog-heading"><div><SectionLabel>Latest New &amp; Blogs</SectionLabel><h2 className="section-heading">The latest blog<br />from us.</h2></div><Button href="/hulio/blog" variant="outline">View All Insights</Button></div><div className="home-grid-gap"><BlogGrid limit={3}/></div></div></section>
    <MovingCTA />
    </>;
}
