import { Button, Counter, Divider, FAQ, Reveal, SectionLabel } from "@/components/shared";
import { Testimonials, UseCases } from "@/components/home-interactions";
import { LogoStrip } from "@/components/logo-strip";
import { PriceToggle } from "@/components/price-toggle";
import { asset, pageMetadata } from "@/lib/site";
import "./home.css";

export const metadata = pageMetadata("AI Agents That Ship Real Business Outcomes");
const platforms = [
  ["Build", "Compose agents visually or in code with built-in tools, memory, planning, and guardrails."],
  ["Connect", "Plug into 200+ systems, any MCP server, and your own APIs. Live data with no brittle integration code."],
  ["Deploy", "Ship to managed runtime or your own VPC. Zero-downtime rollouts, versioning, and instant rollback"],
  ["Monitor", "Trace every step, token, and dollar in real time. Evals, alerts, and outcome metrics out of the box."],
];
const plans = [
  { name: "Starter", price: "$0", suffix: "/ Forever", description: "Perfect for learning, prototypes, and personal projects.", features: ["Up to 3 AI Agents", "10,000 AI steps / month", "5 Projects", "1 Workspace", "Basic AI Models", "Community Templates", "Workflow Builder", "API Access (Limited)", "Webhook Support"], cta: "Start Free" },
  { name: "Pro", price: "$49", suffix: "/ Forever", description: "Everything you need to ship AI into production.", features: ["Unlimited AI Agents", "2M AI Steps / month", "Unlimited Workspaces", "Custom AI Workflows", "REST API", "Role-Based Permissions", "Private Deployments", "Usage Analytics", "Performance Monitoring"], cta: "Start 14-Day Trial" },
  { name: "Enterprise", price: "Custom", suffix: "", description: "Built for large teams with enterprise security and governance.", features: ["SSO (SAML/OIDC)", "SCIM Provisioning", "Organization Policies", "Team Management", "Multi-Region Deployment", "Unlimited AI Steps", "Custom Integrations", "Migration Assistance", "24/7 Premium Support"], cta: "Talk to Sales" },
];

export default function Home() { return <main className="orb-home">
  <section className="orb-container home-hero" aria-labelledby="home-heading"><div className="home-hero-copy"><img className="home-hero-decoration home-decoration-left" src={asset("71OBTqsSojVS2iT4YzFdIwL984")} alt="" /><img className="home-hero-decoration home-decoration-right" src={asset("Y2rwQGttKSmnA8tL9VzFsq2TnUQ")} alt="" /><div className="home-hero-words"><div className="home-announcement"><span>New</span><p>ORBITAL AI 3.0 – Multi-agent runtime</p></div><h1 id="home-heading">AI Agents That Ship<br />Real Business Outcomes</h1><p className="home-hero-description">Build, connect, deploy, and monitor intelligent agents from one platform. Production-grade infrastructure for teams shipping AI into the real world.</p><div className="orb-actions"><Button>Start Building</Button><Button secondary>Book Demo</Button></div></div></div><div className="home-hero-image"><img src={asset("oLjGHEJ7nCzXu1XG8qs5wIrnSs")} alt="MCP, Research, Sales, Ops and Support agents working together" width="5440" height="1892" fetchPriority="high" /></div><Divider /></section>
  <LogoStrip />
  <section id="platform" className="orb-container home-platform"><Divider /><div className="orb-frame home-tinted"><SectionLabel number="01" label="The platform" /><div className="home-platform-heading"><Reveal><h2>One platform for the<br className="orb-desktop-break" /> entire agent lifecycle.</h2></Reveal><p>From first prototype to production at scale no glue code, no stitched-together tools.</p></div><div className="home-platform-cards">{platforms.map(([name, copy], i)=><Reveal key={name}><article><img src={["/orbital/assets/platform-0.svg", "/orbital/assets/platform-1.svg", "/orbital/assets/platform-2.svg", "/orbital/assets/platform-3.svg"][i]} alt="" width="36" height="36" /><h3>{name}</h3><p>{copy}</p></article></Reveal>)}</div></div></section>
  <section id="runtime" className="orb-container home-runtime"><Divider /><div className="orb-frame home-runtime-grid"><div><SectionLabel number="02" label="Runtime" /><div className="home-runtime-copy"><Reveal><h3>A runtime built for many agents working as one.</h3><p>An orchestrator plans work, routes it to agents, and reconciles results with shared memory, tool access, and guardrails.</p></Reveal><ul><li><strong>Parallel orchestration</strong><p>Fan out to dozens of agents, then gather and reconcile results automatically.</p></li><li><strong>Shared memory</strong><p>Durable context that survives restarts, retries, and handoffs between agents.</p></li><li><strong>Deterministic replay</strong><p>Re-run any trace step-by-step to debug, audit, or build an eval from it.</p></li></ul></div></div><div className="home-runtime-image"><img src={asset("ZnPAMLk29J8mXtjDg49Tw1KYF84")} width="861" height="1005" alt="Runtime layers: Goal / Input, Orchestrator, Agent Layer, State & Context, Infrastructure" /></div></div></section>
  <section id="use-case" className="orb-container home-use-section"><Divider /><div className="orb-frame home-tinted"><SectionLabel number="03" label="Use cases" /><Reveal className="home-centered-heading"><h2>Built for the work your<br className="orb-desktop-break" /> team actually does.</h2></Reveal><UseCases /></div></section>
  <section id="benchmarks" className="orb-container home-benchmarks"><Divider /><div className="orb-frame"><SectionLabel number="04" label="Benchmarks" /><div className="home-benchmark-content"><div className="home-feature-row"><Reveal><h3>Higher task success at a lower cost per task.</h3><p>Measured on AgentBench-1.2k across tool use, retrieval, and multi-step planning. Orbital&apos;s orchestration lands more tasks and spends fewer tokens doing it.</p><div className="home-benchmark-stats"><div><strong><Counter value={94} suffix="%" /></strong><p>Task success rate</p></div><div><strong><Counter value={3} suffix="x" /></strong><p>More tasks per dollar</p></div></div></Reveal><img src={asset("9o5djt57SJZTlfV1MAf24NNQXs")} alt="Agent task success and cost efficiency benchmark chart" width="1032" height="812" /></div><div className="home-feature-row home-code-row"><img src={asset("gSGpLTwekrfu4oWIHWqSobl9HsQ")} alt="A TypeScript example that creates and deploys an Orbital agent" width="1032" height="812" /><Reveal><h3>A production agent in a dozen lines.</h3><p>Typed SDKs for TypeScript and Python. Local-first dev, deploy with one command, and the same runtime in every environment.</p><div className="home-docs-actions"><Button>Read the docs</Button><Button secondary>$ npm i @orbital/agents</Button></div></Reveal></div></div></div></section>
  <section id="observability" className="orb-container home-observability"><Divider /><div className="orb-frame home-tinted"><SectionLabel number="05" label="Observability" /><Reveal className="home-centered-heading"><h2>Every run, measured in real time.</h2></Reveal><div className="home-observability-image"><img src={asset("kdjPCROnzBaT7ryNfQzdXmLHiHs")} alt="Orbital observability dashboard showing success rate, runs, latency, and traces" width="4312" height="1800" /></div></div></section>
  <section id="Integrations" className="orb-container home-integrations"><Divider /><div className="orb-frame"><SectionLabel number="06" label="Integrations" /><Reveal className="home-centered-heading"><h2>Native to MCP.<br /> Connected to everything.</h2><p>Bring any MCP server or REST API. 200+ first-party connectors,<br className="orb-desktop-break" /> all governed by the same permissions and audit trail.</p></Reveal><img className="home-integration-image" src={asset("I5kGCgBJzMdf91EynFfYGd4qVro")} alt="An ecosystem of tools and data connectors surrounding the Orbital runtime" width="4312" height="2716" /></div></section>
  <section id="pricing" className="orb-container home-pricing"><Divider /><div className="orb-frame home-tinted"><SectionLabel number="07" label="Pricing" /><Reveal className="home-centered-heading"><h2>Start free. Scale<br />when you ship.</h2></Reveal><div className="home-pricing-grid">{plans.map((plan,i)=><article className={`home-plan ${i===1?'home-plan-pro':''}`} key={plan.name}><div className="home-plan-top"><div className="home-plan-name">{plan.name}{i===1&&<span>Most Popular</span>}</div>{i === 1 ? <PriceToggle /> : <div className="home-plan-price"><h3>{plan.price}</h3><span>{plan.suffix}</span></div>}<p>{plan.description}</p></div><div className="home-plan-features"><p>What&apos;s included:</p><ul>{plan.features.map(feature=><li key={feature}><span aria-hidden="true">✓</span>{feature}</li>)}</ul></div><Button secondary={i!==1}>{plan.cta}</Button></article>)}</div></div></section>
  <section id="testimonial" className="orb-container home-customers"><Divider /><div className="orb-frame"><SectionLabel number="08" label="Customer" /><Reveal className="home-centered-heading"><h2 className="home-customer-heading-desktop">Teams ship faster on Orbital.</h2><h2 className="home-customer-heading-phone">Start free. Scale<br />when you ship.</h2></Reveal><Testimonials /></div></section>
  <FAQ />
</main>; }
