"use client";

import { useLiveReducedMotion as useReducedMotion } from '../motion-preference';
import { useState } from 'react';
import { motion } from 'motion/react';
import { revealSpring } from '../motion-primitives';
import { TestimonialCarousel } from './TestimonialCarousel';
import { FAQItem, HeroDashboard, HeroMark, LoadReveal, Price, Ticker } from './motion';
import { Button, Logo, Reveal, SectionHeading } from '../shared';
import styles from './home.module.css';

const asset = (name: string) => `/alytics/${name}`;
export function Hero() {
  return <section className={styles.hero}><div className={`container ${styles.heroInner}`}>
    <div className={styles.floatingLogos} aria-hidden="true">{['nJN9fw89j7L0b6R9JJh3qGL98.png','rpot5Bf0TIFeRoXSfetpc2GULFo.png','GfeiYrM8yVHItoK8N01yQWI7djQ.png','3xq9uOvolNwNx1mCSkE8bN0BYQ.png'].map((name,i)=><HeroMark key={name} name={name} index={i}/>)}</div>
    <div className={styles.heroCopy}><LoadReveal y={40} delay={0.1}><div className={styles.trusted}><span className={styles.avatars}>{['XreXVnshxtY9J8ZoG3rjAuTzW8E.png','IvVTxoC9vqr4NcKyfF6JMWEc.png','UrClpHTqxXZbq1FAa6sJ9BzS1uk.png'].map(name=><img src={asset(name)} key={name} width="22" height="22" alt="Alytics user" />)}</span>Trusted by 1M+ users</div></LoadReveal>
    <div><LoadReveal y={60} delay={0.2}><h1>Turn Scattered Data Into Smart Decisions</h1></LoadReveal><LoadReveal y={80} delay={0.3}><p>One simple dashboard to track your SaaS growth, MRR, churn and user behavior—without the chaos.</p></LoadReveal></div>
    <LoadReveal y={60} delay={0.4}><div className={styles.heroAction}><Button>Get Started For Free</Button><span><svg width="20" height="16" viewBox="0 0 20 16" aria-hidden="true"><rect width="19" height="14" y="1" rx="2" fill="#126dfb"/><path d="M1 5h17M4 10h3" stroke="white"/></svg>No credit card required</span></div></LoadReveal></div>
    <HeroDashboard/>
    <div className={styles.trustStrip}><h5>Blindly trusted by</h5><div className={styles.trustMask}><Ticker className={styles.trustTrack} label="Trusted companies">{Array.from({length:6},(_,i)=><img key={i} src={asset(`trust-${i}.svg`)} draggable="false" alt={['Kintsugi','CoreOS','Luminary','45 Degrees','Pencil','Layers'][i]} />)}</Ticker></div></div>
  </div></section>;
}
const testimonials = [
  {name:'Carter June',role:'Support Lead, Peakflow',image:'Ja8p9J3F9vN86Z3j6hBjs1zT9SY.png',quote:'"I’ve tried nearly every analytics tool out there, and Alytics is by far the most intuitive. No need for devs to set things up—our marketing team was running insights independently in hours."'},
  {name:'Elena Park',role:'Growth Lead, Launchpad',image:'kVI5rNJF2u29dE47wJKBMhBHIVc.png',quote:'"It’s like product analytics finally caught up with design. We use Alytics not just for numbers—but to tell the story behind them. It’s become our go-to tool for every launch."'},
  {name:'James Nair',role:'Lead Developer, Driftwave',image:'g9u5lc8a7bhRVYmAcLaz2V8Vd0.png',quote:'"We used Alytics to track onboarding drop-off and spotted a friction point instantly. After one small UX tweak, our activation rate jumped by 23%."'},
  {name:'Sarah Bond',role:'CEO, NovaCo',image:'eqelcmPilFO99lTneGHDJtQO7w.png',quote:'"Alytics gave us visibility we didn’t even know we were missing. Within the first week, we discovered which features were actually driving retention. It’s clean and fast."'},
  {name:'Marcus Lee',role:'Head of Design, Stackly',image:'toL76daUzF0G3CNvrUyjLIYRBU.png',quote:'"Since switching to Alytics, we finally understand how users interact with our product. The event tracking is super intuitive and actionable."'},
];
function TestimonialCard({item}:{item:typeof testimonials[number]}) {return <figure className={styles.testimonialCard}><img className={styles.stars} src={asset('7gBs4Qym6w5w5VToXqPFZUirIg.svg')} alt="5 out of 5 stars" width="98" height="18"/><blockquote>{item.quote}</blockquote><figcaption><img src={asset(item.image)} alt="" width="48" height="48"/><div>{item.name}<p>{item.role}</p></div></figcaption></figure>}
export function Testimonials() {
  return <section className={`section ${styles.testimonials}`}><div className="container"><SectionHeading label="Testimonials" title="Hear What Others Say About Us" description="See what top teams say after switching to a smarter product analytics platform."/><div className={styles.testimonialMask}><Ticker className={styles.testimonialTrack} label="Customer testimonial ticker">{testimonials.map(item=><TestimonialCard key={item.name} item={item}/>)}</Ticker></div><div className={styles.mobileTestimonials}><TestimonialCarousel items={[testimonials[0],testimonials[1],testimonials[2],testimonials[4],testimonials[3]].map(item=><TestimonialCard key={item.name} item={item}/>)}/></div></div></section>;
}
const plans = [
 {name:'Starter',monthly:39,yearly:139,description:'Great for small teams getting started.',features:['5,000 tracked users','Core analytics','Simple dashboards','Email support','Weekly reports']},
 {name:'Growth',monthly:99,yearly:199,description:'For fast-growing teams who are scaling.',features:['Everything in starter','50,000 tracked users','Funnel & drop-off analysis','Custom dashboards','Team collaboration tools']},
 {name:'Premium',monthly:299,yearly:599,description:'Great for enterprizes to convert more.',features:['All Growth features','Unlimited tracked users','Dedicated account manager','SLA & compliance support','Advanced integrations']},
];
export function Pricing() {const [yearly,setYearly]=useState(false);const reduced=useReducedMotion();return <section id="pricing" className="section"><div className="container"><SectionHeading label="Our Pricing" title="Choose The Best Plan That Suites You" description="Flexible pricing built for every stage — from startup to scale, no hidden fees."/><Reveal y={60} delay={0.4} threshold={0} className={styles.pricingContent}><div className={styles.billingToggle} aria-label="Billing period"><div className={styles.billingTrack}><motion.div className={styles.billingPill} aria-hidden="true" initial={false} animate={{left:yearly?"47%":"0%",x:yearly?-2:2,width:yearly?"53%":"46%"}} transition={reduced?{duration:0}:revealSpring}/><motion.button type="button" aria-pressed={!yearly} onClick={()=>setYearly(false)} animate={{color:yearly?"#575757cc":"#126dfb"}} transition={reduced?{duration:0}:revealSpring}>Monthly</motion.button><motion.button type="button" aria-pressed={yearly} onClick={()=>setYearly(true)} animate={{color:yearly?"#126dfb":"#575757cc"}} transition={reduced?{duration:0}:revealSpring}>Yearly <motion.span initial={false} animate={{backgroundColor:yearly?"#126dfb":"#126dfb00",color:yearly?"#fff":"#126dfb"}} transition={reduced?{duration:0}:revealSpring}>-20%</motion.span></motion.button></div></div><div className={styles.pricingGrid}>{plans.map((plan,i)=><article key={plan.name} className={`${styles.plan} ${i===1?styles.popular:''}`}>{i===1&&<div className={styles.popularLabel}>Most Popular</div>}<div className={styles.planInner}><div className={styles.planTop}><h3>{plan.name}</h3><div><Price monthly={plan.monthly} yearly={plan.yearly} annual={yearly}/><p>{plan.description}</p></div><Button>Get Started</Button></div><div className={styles.planBottom}><p>What's included</p><ul>{plan.features.map(feature=><li key={feature}><span aria-hidden="true">✓</span>{feature}</li>)}</ul></div></div></article>)}</div></Reveal></div></section>}
export function Comparison(){return <section className="section"><div className="container"><SectionHeading label="Why Alytics" title="A Smarter Way To Grow With Data" description="Turn complex metrics into clear insights that help you make better decisions, faster."/><Reveal y={60} delay={0.4} threshold={0} className={styles.comparison}><div><h3>Other Tools</h3><ul>{['Data lives in too many places','Reporting eats up hours','Insights are too generic','No smart guidance for decisions','Hard to see what’s really working'].map(text=><li key={text}><span aria-hidden="true">×</span>{text}</li>)}</ul></div><div className={styles.ours}><h3><Logo/></h3><ul>{['All your metrics, one platform','Track what drives growth','Insights tailored to your goals','AI suggests your next move','Clear path to consistent growth'].map(text=><li key={text}><span aria-hidden="true">✓</span>{text}</li>)}</ul></div></Reveal></div></section>}
const faqs=[
 ['How does your platform track feature usage?','We automatically collect interaction data across your product and visualize which features are being used most — no manual tagging needed.'],
 ['Do I need technical skills to use Alytics?',"Not at all. Alytics is built for teams of all sizes. Whether you're in marketing, product, or operations, the interface is intuitive and requires no coding."],
 ['Can Alytics integrate with tools we already use?','Yes. Alytics integrates with major tools like Stripe, Google Analytics, HubSpot, and more. You can also connect via API or no-code platforms.'],
 ['Is my data secure on Alytics?','Absolutely. We use enterprise-grade encryption and follow best practices in data privacy and compliance.'],
 ['Can I try Alytics before committing?','Yes, we offer a free trial so you can explore all features before upgrading to a paid plan.'],
];
export function FAQ(){const [opened,setOpened]=useState([0]);return <section id="faq" className="section"><div className="container"><SectionHeading label="FAQ’s" title="Common Questions With Clear Answers" description="Here are answers to the most common things people ask before getting started."/><Reveal y={60} delay={0.4} threshold={0} className={styles.faqs}>{faqs.map(([q,a],i)=><FAQItem key={q} question={q} answer={a} index={i} open={opened.includes(i)} onToggle={()=>setOpened(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}/>)}</Reveal></div></section>}
