'use client';
import { useEffect, useState } from 'react';
import { asset } from '@/lib/assets';
import { Arrow } from './shared';
const testimonials = [
    { quote: 'Working with Hulio was seamless. They designed our site using Craft CMS, letting us manage everything with full control.', name: 'Emily Rodriguez', role: 'Product Designer', image: 'SzYVrwgREjJx05TjHIaro4yz60.png' },
    { quote: 'Hulio handled our branding and design with real attention to detail. They built the site on Craft CMS, which gave us smooth editing, great flexibility.', name: 'Michael Thompson', role: 'Web Developer', image: 'E5Blj8AAEzEskI9AwIHHLXqEV8.png' },
    { quote: 'Hulio handled our website and branding. They used Craft CMS instead of WordPress, giving us control and a smoother experience.', name: 'Assistant Manager', role: 'Assistant Manager', image: 'zpSxgXY45GGlnvWENTEFznKaoEY.png' },
    { quote: 'From branding to app design, Hulio brought our vision to life. Craft CMS made managing the site simple and customizable.', name: 'John Anderson', role: 'CEO - TechNova', image: 'epTWmJHdnwzkKGdFqCnqgL5mkn0.png' },
];
export function Testimonials() { const [index, setIndex] = useState(0); const [paused, setPaused] = useState(false); useEffect(() => { if (paused || matchMedia('(prefers-reduced-motion: reduce)').matches)
    return; const timer = setInterval(() => setIndex(i => (i + 1) % testimonials.length), 5000); return () => clearInterval(timer); }, [paused, index]); return <div className="testimonials-carousel" aria-roledescription="carousel" aria-label="Client testimonials" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onFocusCapture={() => setPaused(true)} onBlurCapture={e => { if (!e.currentTarget.contains(e.relatedTarget))
    setPaused(false); }}><div className="slider-controls"><button type="button" aria-label="Previous testimonial" onClick={() => setIndex((index + 3) % 4)}><span className="back-arrow"><Arrow /></span></button><button type="button" aria-label="Next testimonial" onClick={() => setIndex((index + 1) % 4)}><Arrow /></button></div><div className="testimonial-pair" aria-live={paused ? 'polite' : 'off'}>{[0, 1].map(offset => { const t = testimonials[(index + offset) % 4]; return <article key={t.name} className="testimonial-card"><span className="quote-icon" aria-hidden="true">❝</span><p>{t.quote}</p><div className="testimonial-author"><img src={asset(t.image)} alt="" width="56" height="56"/><div><strong>{t.name}</strong><small>{t.role}</small></div><div className="testimonial-rating"><span aria-label="5 stars">★★★★★</span><small>5 Start Rating</small></div></div></article>; })}</div><div className="slider-dots">{testimonials.map((t, i) => <button type="button" key={t.name} aria-label={`Scroll to page ${i + 1}`} aria-pressed={index === i} onClick={() => setIndex(i)}/>)}</div></div>; }
export function KeywordTicker() { const words = ['DEVELOPMENT', 'STUDIO', 'STRATEGY', 'BRANDING', 'DIGITAL AGENCY', 'TYPOGRAPHY', 'DESIGN', 'INTERACTION', 'DIGITAL STUDIO', 'SOLUTION']; return <div className="keyword-ticker"><div className="ticker-track">{[0, 1].map(copy => <div className="ticker-group" key={copy} aria-hidden={copy === 1}>{words.map(word => <span key={word}>{word}<b aria-hidden="true">✦</b></span>)}</div>)}</div></div>; }
export function MovingCTA() { return <section className="moving-cta" aria-label="Let's work together">{[0, 1].map(row => <a href="/hulio/contact" key={row} className={`cta-track cta-track-${row}`}><span>{Array.from({ length: 5 }, (_, i) => <span key={i}>Let’s work together. <b aria-hidden="true">✦</b> </span>)}</span></a>)}</section>; }
